apiVersion: v2
name: todo-app
description: A Helm chart for Todo Application with Spring Boot and Angular
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.5.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: prometheus
    version: "22.6.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.56.5"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: jaeger
    version: "0.71.5"
    repository: "https://jaegertracing.github.io/helm-charts"
    condition: jaeger.enabled
  - name: opentelemetry-collector
    version: "0.62.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-collector.enabled 